In [141]:
#basic imports
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
import torch.nn.functional as F
device = torch.device("mps")

In [142]:
normal_df = pd.read_csv('ptbdb_normal.csv')
abnormal_df = pd.read_csv('ptbdb_abnormal.csv')

In [143]:
normal_df.head()

,1.000000000000000000e+00,9.003241658210754395e-01,3.585899472236633301e-01,5.145867168903350830e-02,4.659643396735191345e-02,1.268233358860015869e-01,1.333063244819641113e-01,1.191247999668121338e-01,1.106158867478370667e-01,1.130470037460327148e-01,...,0.000000000000000000e+00.56,0.000000000000000000e+00.57,0.000000000000000000e+00.58,0.000000000000000000e+00.59,0.000000000000000000e+00.60,0.000000000000000000e+00.61,0.000000000000000000e+00.62,0.000000000000000000e+00.63,0.000000000000000000e+00.64,0.000000000000000000e+00.65
0,1.000000,0.794681,0.375387,0.116883,0.000000,0.171923,0.283859,0.293754,0.325912,0.345083,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.909029,0.791482,0.423169,0.186712,0.000000,0.007836,0.063032,0.077002,0.074957,0.077342,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.478893,0.056760,0.064176,0.081289,0.072732,0.055619,0.048774,0.054478,0.041643,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.000000,0.867238,0.201360,0.099349,0.141336,0.120934,0.108516,0.096393,0.093436,0.100828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.948983,0.505265,0.004176,0.022513,0.059550,0.107298,0.110385,0.111293,0.116558,0.118192,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [144]:
normal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4045 entries, 0 to 4044
Columns: 188 entries, 1.000000000000000000e+00 to 0.000000000000000000e+00.65
dtypes: float64(188)
memory usage: 5.8 MB

In [145]:
abnormal_df.head()

,9.322328567504882812e-01,8.696785569190979004e-01,8.861859440803527832e-01,9.296264052391052246e-01,9.087749719619750977e-01,9.339704513549804688e-01,8.010425567626953125e-01,7.497828006744384766e-01,6.872285008430480957e-01,6.350998878479003906e-01,...,0.000000000000000000e+00.117,0.000000000000000000e+00.118,0.000000000000000000e+00.119,0.000000000000000000e+00.120,0.000000000000000000e+00.121,0.000000000000000000e+00.122,0.000000000000000000e+00.123,0.000000000000000000e+00.124,0.000000000000000000e+00.125,1.000000000000000000e+00.1
0,1.000000,0.606941,0.384181,0.254237,0.223567,0.276836,0.253430,0.184826,0.153349,0.121872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.000000,0.951613,0.923963,0.853303,0.791859,0.734255,0.672043,0.685100,0.670507,0.667435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.977819,0.899261,0.230129,0.032348,0.142329,0.223660,0.328096,0.367837,0.381701,0.389094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.935618,0.801661,0.805815,1.000000,0.722741,0.480789,0.454829,0.319834,0.266874,0.308411,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.925265,0.433352,0.073620,0.079197,0.136643,0.182934,0.182934,0.182376,0.196877,0.203569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [146]:
abnormal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10505 entries, 0 to 10504
Columns: 188 entries, 9.322328567504882812e-01 to 1.000000000000000000e+00.1
dtypes: float64(188)
memory usage: 15.1 MB

In [147]:
abnormal_df.columns = range(1,189)
normal_df.columns = range(1,189)

In [148]:
normal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4045 entries, 0 to 4044
Columns: 188 entries, 1 to 188
dtypes: float64(188)
memory usage: 5.8 MB

In [149]:
abnormal_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10505 entries, 0 to 10504
Columns: 188 entries, 1 to 188
dtypes: float64(188)
memory usage: 15.1 MB

### inserting labels 0-normal 1- abnormal

In [150]:
normal_df['label'] = np.array([0 for i in range(len(normal_df))])
abnormal_df['label'] = np.array([1 for i in range(len(abnormal_df))])

In [151]:
df = pd.concat([normal_df,abnormal_df])
df = df.sample(frac=1)

In [152]:
df.head()

,1,2,3,4,5,6,7,8,9,10,...,180,181,182,183,184,185,186,187,188,label
555,1.000000,0.401527,0.000000,0.047428,0.106913,0.116559,0.102894,0.101688,0.104100,0.096865,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
6658,1.000000,0.904077,0.895683,0.721223,0.453837,0.286571,0.208034,0.181055,0.323741,0.368106,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
863,0.968775,1.000000,0.847078,0.780625,0.686149,0.630104,0.538831,0.493195,0.419536,0.384307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
7380,1.000000,0.600169,0.161454,0.047337,0.101437,0.189349,0.222316,0.113271,0.164835,0.145393,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
43,1.000000,0.784921,0.184551,0.057354,0.025902,0.054579,0.144311,0.179001,0.175763,0.179463,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [153]:
df.index = range(len(df))

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14550 entries, 0 to 14549
Columns: 189 entries, 1 to label
dtypes: float64(188), int64(1)
memory usage: 21.0 MB

In [155]:
from sklearn.model_selection import train_test_split
train_df,test_df = train_test_split(df,test_size=0.33)

In [156]:
train_df['label'].value_counts()

label
1    7058
0    2690
Name: count, dtype: int64

In [157]:
test_df['label'].value_counts()

label
1    3447
0    1355
Name: count, dtype: int64

In [158]:
class ECG_Dataset(Dataset):
    def __init__(self,df):
        self.df = df
        self.features = df.drop('label',axis=1).values
        self.labels = df['label'].values
    def __len__(self):
        return len(self.df)
    def __getitem__(self,idx):
        feature = torch.Tensor(self.features[idx])
        label = torch.tensor(self.labels[idx])
        return feature,label

In [159]:
train_dataset = ECG_Dataset(train_df)
test_dataset = ECG_Dataset(test_df)

In [160]:
def pad_collate(batch):
    data = [item[0] for item in batch]
    labels = [item[1] for item in batch]
    max_size = max([item.size(0) for item in data])
    padded_data = [F.pad(item, (0, max_size - item.size(0))) for item in data]
    return torch.stack(padded_data), torch.tensor(labels)

In [161]:
train_batch_size = 150
test_batch_size = 150
train_loader = DataLoader(train_dataset,batch_size=train_batch_size,shuffle=True,collate_fn=pad_collate)
test_loader = DataLoader(test_dataset,batch_size=test_batch_size,shuffle=False,collate_fn=pad_collate)

In [162]:
class LSTM(nn.Module):
    
    def __init__(self,in_size,hidden_size,out_size=2,num_layers=1,bidirectional=False,p=0.4):
        super(LSTM,self).__init__()
        self.num_layers = num_layers
        self.num_dir = 2 if bidirectional else 1
        self.hidden_size = hidden_size
        self.lstm = nn.LSTM(in_size,hidden_size,num_layers=num_layers,bidirectional=bidirectional,batch_first=True)
        self.fc = nn.Linear(self.num_dir * self.hidden_size,out_size)
        self.dropout = nn.Dropout(p)
    def forward(self,x,hidden):
        lstm_out,hidden = self.lstm(x,hidden)
        lstm_out = self.dropout(lstm_out)
        pred = self.fc(lstm_out[:,-1,:])
        return pred
    def init_hidden(self,batch_size):
        hidden = (torch.zeros(self.num_dir*self.num_layers,batch_size,self.hidden_size).to(device),
                 torch.zeros(self.num_dir*self.num_layers,batch_size,self.hidden_size).to(device))
        return hidden

In [172]:
model = LSTM(in_size=188,hidden_size=32,out_size=2,num_layers=1,bidirectional=False,p=0.4).to(device)

In [173]:
num_epochs = 3
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [174]:
for epoch in range(num_epochs):
    model.train()
    for X_train,y_train in train_loader:
        X_train,y_train = X_train.to(device),y_train.to(device)
        X_train = X_train.unsqueeze(1)
        hidden = model.init_hidden(X_train.size(0))
        y_pred = model.forward(X_train,hidden)
        loss = criterion(y_pred,y_train)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f"epoch : {epoch+1} loss : {loss.item()}")

epoch : 1 loss : 0.42526865005493164
epoch : 2 loss : 0.27952319383621216
epoch : 3 loss : 0.16755595803260803

In [175]:
from sklearn.metrics import classification_report

all_preds = []
all_labels = []

model.eval()
with torch.no_grad():
    for X_test, y_test in test_loader:
        X_test, y_test = X_test.to(device), y_test.to(device)
        hidden = model.init_hidden(X_test.size(0))
        
        # Add channel dimension if needed
        X_test = X_test.unsqueeze(1) 
        
        # Forward pass
        pred = model(X_test, hidden)
        pred = torch.argmax(pred, dim=1)
        
        # Collect predictions and labels
        all_preds.extend(pred.cpu().numpy())
        all_labels.extend(y_test.cpu().numpy())

# Use classification_report with the collected predictions and labels
print(classification_report(all_labels, all_preds))

              precision    recall  f1-score   support

           0       0.98      0.95      0.97      1355
           1       0.98      0.99      0.99      3447

    accuracy                           0.98      4802
   macro avg       0.98      0.97      0.98      4802
weighted avg       0.98      0.98      0.98      4802

In [176]:
X = df.drop('label',axis=1)
y = df['label']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33)

In [177]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
pred_dtree = dtree.predict(X_test)
print(classification_report(y_test,pred_dtree))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1367
           1       1.00      1.00      1.00      3435

    accuracy                           1.00      4802
   macro avg       1.00      1.00      1.00      4802
weighted avg       1.00      1.00      1.00      4802